version: '3.8'

services:
  jaeger:
    container_name: cucumber-playwright-jaeger
    image: jaegertracing/all-in-one:1.45
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HTTP_HOST_PORT=:4318
      - COLLECTOR_OTLP_GRPC_HOST_PORT=:4317
    ports:
      - "16686:16686"   # Jaeger UI
      - "14250:14250"   # OTLP gRPC
      - "6831:6831/udp" # Jaeger agent
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP

  otel-collector:
    container_name: cucumber-playwright-otelcol
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "24317:4317"  # OTLP gRPC
      - "24318:4318"  # OTLP HTTP
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: cucumber-playwright-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: cucumber-playwright-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: