version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.45
    ports:
      - "16686:16686"    # Jaeger UI
      - "4317:4317"      # OTLP gRPC receiver
      - "4318:4318"      # OTLP HTTP receiver
      - "9411:9411"      # Zipkin receiver
      - "14268:14268"    # legacy Jaeger HTTP collector
      - "6831:6831/udp"  # Thrift/UDP collector
    networks:
      - observability

networks:
  observability: