global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'otel-collector-prometheus-exporter'
    static_configs:
      - targets: ['otel-collector:9464']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:9464']
    scrape_interval: 5s

remote_write:
  - url: http://prometheus:9090/api/v1/write