global:
  scrape_interval: 5s

remote_write:
  - url: http://localhost:9090/api/v1/write

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['host.docker.internal:24318']

  - job_name: 'k6'
    static_configs:
      - targets: ['host.docker.internal:9464']